name: Portfolio CI

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Installer les dépendances
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
